---
# tasks file for squid
- name: Install squid
  package: 
    name: squid
    state: present

- name: Install squid.conf
  tags: squid
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: 0644
    validate: squid -k parse -f %s
  notify:
    - restart squid
 
